[package]
name = "swim-c-rt"
version = "0.1.0"
authors = ["Chris Sachs <chris@swim.ai>"]
edition = "2018"

[dependencies]
swim-core = { path = "../../lib/core" }
swim-mem = { path = "../../lib/mem" }
swim-c = { path = "../../sys/c" }
